




"use strict";function _instanceof(e,t){return null!=t&&"undefined"!=typeof Symbol&&t[Symbol.hasInstance]?!!t[Symbol.hasInstance](e):e instanceof t}function _classCallCheck(e,t){if(!_instanceof(e,t))throw new TypeError("Cannot call a class as a function")}function _defineProperties(e,t){for(var n=0;n<t.length;n++){var l=t[n];l.enumerable=l.enumerable||!1,l.configurable=!0,"value"in l&&(l.writable=!0),Object.defineProperty(e,l.key,l)}}function _createClass(e,t,n){return t&&_defineProperties(e.prototype,t),n&&_defineProperties(e,n),e}var LevusHorizontalScroll=function(){function e(t){_classCallCheck(this,e),this.scroll=document.querySelector(t),this.ul=this.scroll.querySelector(".levus-horizontal-scroll ul"),this.li=this.ul.querySelectorAll("li")}return _createClass(e,[{key:"clone",value:function(){var e=this;this.li.forEach(function(t){return e.ul.append(t.cloneNode(!0))}),this.li=this.scroll.querySelectorAll(".levus-horizontal-scroll li")}},{key:"translate",value:function(){this.ul.style.left="-25%"}},{key:"buttons",value:function(){var e=this,t=document.createElement("span");t.setAttribute("class","left"),this.scroll.prepend(t);var n=document.createElement("span");n.setAttribute("class","right"),this.scroll.prepend(n),this.scroll.addEventListener("click",function(t){"left"==t.target.className&&(e.ul.prepend(e.ul.lastElementChild),e.ul.style.transition="",e.ul.style.transform="translateX(-25%)",setTimeout(function(){e.ul.style.transform="translateX(0)",e.ul.style.transition=".5s"},50))}),this.scroll.addEventListener("click",function(t){"right"==t.target.className&&(e.ul.append(e.ul.firstElementChild),e.ul.style.transition="",e.ul.style.transform="translateX(25%)",setTimeout(function(){e.ul.style.transform="translateX(0)",e.ul.style.transition=".5s"},50))})}},{key:"init",value:function(){this.li.length<=5&&this.clone(),this.translate(),this.buttons()}}]),e}(),
skills=document.querySelectorAll(".levus-skills");if(skills.length>0){var delay=function(e){for(var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:2,n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:1,l=function(t){setTimeout(function(){e.innerHTML=t},t*n*30)},s=0;s<=t;s++)l(s)},start=document.documentElement.clientHeight;skills&&window.addEventListener("scroll",function(){var e=Math.floor(skills[0].getBoundingClientRect().top),t=Math.floor(start-e+10);0!==t&&1!==t&&2!==t&&3!==t&&4!==t&&5!==t&&6!==t&&7!==t&&8!==t&&9!==t&&10!==t||skills.forEach(function(e){return delay(e,e.dataset.result,e.dataset.speed)})})}

var wrapper=document.getElementById("levus-testimonials");if(wrapper){var items=wrapper.querySelectorAll("#levus-testimonials li"),ul=wrapper.querySelector("ul");items.forEach(function(e){return ul.append(e.cloneNode(!0))}),items=wrapper.querySelectorAll("#levus-testimonials li"),setInterval(function(){var e=ul.lastElementChild;ul.prepend(e),ul.style.transition="none",ul.classList.add("move"),setTimeout(function(){ul.classList.remove("move"),ul.style.transition=".5s"},4e3)},5e3)}var tabs=document.querySelectorAll(".tabs li");if(tabs.length>0){var panes=document.querySelectorAll(".tabs .panes > div");tabs.forEach(function(e,t){return e.addEventListener("click",function(){tabs.forEach(function(e){return e.classList.remove("active")}),tabs[t].classList.add("active"),panes.forEach(function(e){return e.classList.remove("active")}),panes[t].classList.add("active")})})}var months=document.querySelectorAll(".months li"),now=(new Date).getMonth();if(months.length>0){var _panes=document.querySelectorAll(".months .panes > section");months.forEach(function(e){return e.classList.remove("active")}),months[now].classList.add("active"),_panes.forEach(function(e){return e.classList.remove("active")}),_panes[now].classList.add("active"),months.forEach(function(e,t){return e.addEventListener("click",function(){months.forEach(function(e){return e.classList.remove("active")}),months[t].classList.add("active"),_panes.forEach(function(e){return e.classList.remove("active")}),_panes[t].classList.add("active")})})}var accordeon=document.getElementsByTagName("dl");if(accordeon.length>0){var question=accordeon[0].querySelectorAll("dt"),answer=accordeon[0].querySelectorAll("dd"),span=accordeon[0].querySelectorAll("span");question.forEach(function(e,t){return e.addEventListener("click",function(){answer.forEach(function(e){return e.classList.remove("active")}),answer[t].classList.add("active"),span.forEach(function(e){return e.innerHTML="+"}),span[t].innerHTML="-"})})}
// init
document.getElementById("scroll-1")&&new LevusHorizontalScroll("#scroll-1").init(),
document.getElementById("scroll-2")&&new LevusHorizontalScroll("#scroll-2").init(),
document.getElementById("scroll-3")&&new LevusHorizontalScroll("#scroll-3").init();